### ISSUE TITLE
release?

### ISSUE THREAD

**Issue by ghost** [syncopika/basic_screen_recorder_windows#4] opened 2023-04-05 15:43 UTC
could you provide us with a release

**Comment by syncopika** [comment] 2023-04-05 23:02
hi,

I sure can! I'll post back here when that's done.

In the meantime though, if you just were looking for a binary to try out, I've provided one in the repo already that you can download: https://github.com/syncopika/basic_screen_recorder_windows/blob/main/basic_screen_recorder.exe

Thank you for your interest! :)

**Comment by syncopika** [comment] 2023-04-06 02:21
hey @cyberhardt,

A release is now available at https://github.com/syncopika/basic_screen_recorder_windows/releases/tag/1.0.0

thanks again for your interest!

**Comment by ghost** [comment] 2023-04-06 05:05
aha, I didn't even notice that .exe in there. thanks, i'll try it out.

**Comment by ghost** [comment] 2023-04-07 09:03
so, I tried opening it but was hit with half a dozen dll errors. MSVCP140D.dll, VCRUNTINE140D.dll, VCRUNTIME140_1D.dll, ucrtbased.dll. Tried installing all visual studio c++ drivers from 2022 to 2008, including x86 versions, with no avail. will try restarting and see if it works.

**Comment by syncopika** [comment] 2023-04-07 12:06
hi,

I really appreciate you taking the time to try it out and providing detailed feedback about the issue (and apologies for having to go through all that!!).

it looks like I put up a debug build instead of release :(

I'll try to get that fixed by today (and will try to test on another PC to make sure it works).

thanks again and sorry about that!

**Comment by syncopika** [comment] 2023-04-07 13:08
ok, so I _think_ I got this right this time 🤞. added the updated binaries to https://github.com/syncopika/basic_screen_recorder_windows/releases/tag/1.0.0

**Comment by ghost** [comment] 2023-04-08 08:59
Right, it opened this time. gonna test it rn

**Comment by ghost** [comment] 2023-04-08 10:27
At first I tried running it without ffmpeg. It did work, but, as expected, it created a .wav and a folder with a bunch of bitmap pictures. moving it to the folder containing ffmpeg.exe, it created an .mp4 file as well as the others - I believe it would be essential to be able to set to which folder the results are saved to. and some kind of popup or signal to let you know the capture is finished (well I guess you can tell by the ffmpeg window popping up). this and a timer to start the video - after all, you wouldn't want to capture the program's window as well. 1 to 2 seconds of delay or an automatic minimize function should work.

weirdly enough it did save to my downloads folder a couple times, but as an error I believe. something that was corrected by a restart, after which it went back to saving on the ffmpeg folder. maybe i just forgot to close the instance that i originally opened from my downloads folder.

settings seem to be working as intended; cleanup clean things up, show cursor shows cursor. one of the most powerful features of this program, to be honest, isn't even recording video, but being able to record uncompressed, 32-bit PCM audio and take incredibly sharp uncompressed bitmap pictures. the video itself seems to have one big issue, in fact: it runs at 8.333 FPS. I tried different settings and they all would create an 8.3 fps video for some reason.

this, and the AAC audio has too low of a bitrate (120 kbps). I think it would be nice if the output was 320kbps, or if you could at least set it to be that way, or even let it uncompressed or in flac (that would require a flac converter to be on the same folder I suppose). one way to do this without bloating the application with embedded configs is to be able to link a config file that the application could read. this is done in another software I found called yt-dlp-gui: you create a folder named "configs" and set yt-dlp parameters there in .txt format. then, in the GUI, you select "configuration" and it will display a list of the configurations you created, the file names being the configuration names. that way, you could, for example, set it to create a .mkv with certain AVC encoding parameters and certain AAC encoding parameters - in yt-dlp-gui, for instance, it works as to define maximum resolution, file format, whether it would download avc, av1, vp9, mp4, webm, and other yt-dlp stuff. just dont name it "configs" cause it would conflict with yt-dlp-gui lol.

regarding overall encode quality and colour accuracy, it doesn't look bad but there's definitely a noticeable saturation/gamma loss, as well as a sharpness decrease. not that major, but I could notice them. try recording this same github page, and take a look at the red and green colours (and compare it to the original page). red, specifically, looks almost orange in some cases. I've tested it both on a static webpage and on an anime episode. perhaps this could be corrected by changing the variables on options? I used the stock configuration.

when using the screen selector, it will only let you select spaces between the taskbar and the top corner of the program's window, excluding the top corner of the window (where the minimize, maximize, close buttons are - i forgot the name of it lel); it would be nice if it was able to let you select all corners of the display (like when you take a screenshot with snipping tool).

regarding video editing, the mkv format would definitely be more useful than the mp4 one.

as of now, the only actually important issue is the fact the video outputs at 8 fps, but, if you manage to fix all the things I've mentioned, or at least the most pressing ones, it would become an insanely useful program to take short clips. it would be also really useful, albeit as a bit of an unintentional feature, to be able to only record .wav audio or only take .bmp screenshots. I'm yet to see a program that can do that.

that said, the time limit, at least considering how the program works right now, shouldn't be extended. the fact it produces 500mb folders with the .bmp pics for 5 seconds of video could be an issue for ssd's, and that's because the videos are at 8fps. I'm not sure how you would change that, perhaps converting it on-the-fly?

whew, textwall.

**Comment by ghost** [comment] 2023-04-08 10:35
lastly, it would also be useful to associate shortcuts with the program's functions. like, F-something to start capture, F-something to stop it, or control-something. taking into consideration my previous post, there could be shortcuts to print screen in .bmp, capture .wav audio, and so on.

**Comment by syncopika** [comment] 2023-04-08 13:53
wow, thank you so much for the insanely detailed and precise feedback; it's super helpful and I'm really grateful!

- great point about specifying an output directory and adding a delay or auto-minimize! I remember looking up how to minimize a window in Win32 not too long ago but forgot to implement it lol.

- the output of the application should be based on the directory the app lives in - so if it was in your downloads folder, I'd say the output being there was expected behavior (as you hinted at by perhaps not closing the instance that was there initially).

- for the framerate, did you try messing with the interval to take screenshots at?
![image](https://user-images.githubusercontent.com/8601582/230724421-86092dd1-76f1-441a-89fb-b857239b3d6e.png)

changing this value _should_ change the framerate and at least in my experience it takes some trial-and-error to get the frame rate right to sync with the audio. not sure this is a great approach but I lack other ideas at the moment lol.

- good points about the configs for audio and video and the overall encode quality/color accuracy as well as the screen selector issue (I don't think I noticed that before because I've only been taking fairly small captures). Not too sure about the encode quality/color accuracy (I have a feeling changing the variables on options won't help here) and after you mentioned it I can also confirm things appear less sharp - that's definitely worth looking into. maybe an ffmpeg thing?

- agree with being able to just record audio or just take screenshots - that feature should definitely be doable.

- I was definitely worried about memory usage blowing up with regards to the recording duration and am glad you caught that - yeah not sure atm how I'd go about resolving that lol. might have to check out some similar apps for ideas.

- appreciate the idea on shortcuts as well.

thanks again for taking the time to try the app and writing a review! I'm very glad to know it can be useful to others as well. :)

**Comment by ghost** [comment] 2023-04-09 07:47
I didn't change the interval cause, to be very fair, I had no idea what was its purpose. that said, as things currently are, supposing the growth as linear, 30 fps 5seconds video would generate a roughly 3.75x-4x larger .bmp folder, which means almost 2.5 gigabytes per 5 seconds capture considering 500mb one per 5 seconds at 8fps. 30 seconds at 30fps would result in a 15gb .bmp folder. well, it's not thaaaaat much to be fair. that said, the actual video output hardly justifies that much data being written, and I believe the program would benefit of a better encoding process. like, if you're creating uncompressed wavs and bmps, why not make good use of them and create equally high-quality video?

I think that some of this may fall out of your scope with this project, and, if so, that's fine. it's just that there are some interesting things that this program could do, that aren't done by others or are done improperly. 

the sharpness/colour issue is most likely due to the video encoding settings. the screenshots look fine - well, they are bmps, it's basically copying your screen pixel by pixel. can't really go wrong with that.

**Comment by syncopika** [comment] 2023-04-09 11:56
fair point and I definitely could've made it clearer what the purpose of the interval value is 😄. thanks!

**Closed as completed by syncopika** 2023-04-09 11:56 UTC
